name: News Aggregator Worker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # каждые 10 минут

concurrency:
  group: news-worker
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4 gspread google-auth

      - name: Run worker
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python worker.py
